@echo off
@echo Configurando ambiente...
set API_PEDIDOVENDA_HOST=127.0.0.1
set API_PEDIDOVENDA_PORT=8080
set API_PEDIDOVENDA_ORACLE=MGVEN/MEGAVEN@PC_LEANDROA:1521/DESENV
set API_ANALISECREDITO_PATH=/api/v0
set API_ANALISECREDITO_NOME=credito
set API_ANALISECREDITO_HOST=127.0.0.1
set API_ANALISECREDITO_PORT=8081

ms-pedidovenda -porta 8080
