
$env:API_ANALISECREDITO_PORT=8081; 
$env:API_ANALISECREDITO_HOST=127.0.0.1; 
$env:API_ANALISECREDITO_ORACLE='MGVEN/MEGAVEN@PCLOPEZ:1521/ORCL';
$env:API_ANALISECREDITO_PATH='/api/v0'; 
$env:API_ANALISECREDITO_NOME='credito'; 
$env:API_ANALISECREDITO_HOST=127.0.0.1; 
$env:API_ANALISECREDITO_PORT=8081

.\ms-analisecredito.exe -porta 8081